# Generated by Django 3.2.2 on 2022-01-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='programs',
            field=models.ManyToManyField(to='programs.Program'),
        ),
    ]
