# Generated by Django 3.2.2 on 2022-01-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(default='', max_length=250)),
                ('task_create_date', models.DateField()),
                ('task_due_date', models.DateField()),
                ('complete_date', models.DateField()),
                ('status', models.CharField(default='', max_length=200)),
                ('assigned_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
